In [314]:
import pandas as pd
import seaborn as sns
from pandas.plotting import scatter_matrix
from matplotlib import pyplot

# Informações sobre o DataSet

Para os exemplos apresentados no presente módulo, será utilizado o conjunto de dados: Breast Cancer Wisconsin (Street et al. 1992, Mangasarian et al. 1995)

Fonte:
https://archive.ics.uci.edu/dataset/17/breast+cancer+wisconsin+diagnostic

* No conjunto Breast Cancer Wisconsin cada unidade amostral consiste em um tecido de massa mamária e os atributos (as variáveis) correspondem as características, extraídas a partir de imagens digitalizadas, dos núcleos celulares (raio, textura, perímetro etc.) contidos em cada tecido. As classes associadas a cada tecido informam o diagnóstico do tecido (maligno ou benigno).

In [315]:
dados = pd.read_csv('data/breast-cancer.csv')

In [316]:
#verificando a dimensão do DataSet
#(número de unidades amostrais, número de atributos)
dados.shape

(569, 32)

In [317]:
#verificando o número de unidades amostrais não nulas para cada atributo e o seu tipo.
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   sample_id                569 non-null    int64
 1   mean_radius              569 non-null    float64
 2   mean_texture             569 non-null    float64
 3   mean_perimeter           569 non-null    float64
 4   mean_area                569 non-null    float64
 5   mean_smoothness          569 non-null    float64
 6   mean_compactness         569 non-null    float64
 7   mean_concavity           569 non-null    float64
 8   mean_concave_points      569 non-null    float64
 9   mean_symmetry            569 non-null    float64
 10  mean_fractal_dimension   569 non-null    float64
 11  radius_error             569 non-null    float64
 12  texture_error            569 non-null    float64
 13  perimeter_error          569 non-null    float64
 14  area_error               569 non-null    float64
 15  smoothness_error         569 non-null    float64
 16  compactness_error        569 non-null    float64
 17  concavity_error          569 non-null    float64
 18  concave_points_error     569 non-null    float64
 19  symmetry_error           569 non-null    float64
 20  fractal_dimension_error  569 non-null    float64
 21  worst_radius             569 non-null    float64
 22  worst_texture            569 non-null    float64
 23  worst_perimeter          569 non-null    float64
 24  worst_area               569 non-null    float64
 25  worst_smoothness         569 non-null    float64
 26  worst_compactness        569 non-null    float64
 27  worst_concavity          569 non-null    float64
 28  worst_concave_points     569 non-null    float64
 29  worst_symmetry           569 non-null    float64
 30  worst_fractal_dimension  569 non-null    float64
 31  diagnosis                569 non-null    object
dtypes: float64(30), int64(1), object(1)
memory usage: 142.4+ KB

In [318]:
# visualizando as observações de uma variável categórica
dados['diagnosis'].unique()

array(['malignant', 'benign'], dtype=object)

In [319]:
# Esta função retorna o valor da contagem para cada item exclusivo presente na coluna.
# Os valores são exibidos em ordem decrescente para que o elemento mais frequente venha primeiro.
# Isso exclui os valores nulos.
dados['diagnosis'].value_counts()

diagnosis
benign       357
malignant    212
Name: count, dtype: int64

In [320]:
#visualizando as 5 primeiras observação do dataset
dados.head(5)

,sample_id,mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,mean_compactness,mean_concavity,mean_concave_points,mean_symmetry,...,worst_texture,worst_perimeter,worst_area,worst_smoothness,worst_compactness,worst_concavity,worst_concave_points,worst_symmetry,worst_fractal_dimension,diagnosis
0,842302,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,malignant
1,842517,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,malignant
2,84300903,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,malignant
3,84348301,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,malignant
4,84358402,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,malignant

# Eliminação manual de atributos

Diversos conjuntos de dados do mundo real podem ter atributos que, por serem claramente irrelevantes, não apresentam qualquer benefício para uma tarefa de classificação ou de extração de conhecimento.

Por exemplo, o conjunto de dados Breast Cancer contém o atributo sample_id, um valor numérico que identifica o tecido analisado. Como tal valor será único para cada objeto e o mesmo não possui qualquer sentido comparativo, ele pode ser eliminado.

Em Python, isso pode ser realizado por meio do código a seguir.

In [321]:
# removendo a coluna sample_id, a qual nao eh necessaria para realizar o diagnostico
del dados['sample_id']

In [322]:
#verificando a dimensão do DataSet
dados.shape

(569, 31)

In [323]:
#visualizando as 5 primeiras observação do dataset após a eliminação do atributo sample_id
dados.head(5)

,mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,mean_compactness,mean_concavity,mean_concave_points,mean_symmetry,mean_fractal_dimension,...,worst_texture,worst_perimeter,worst_area,worst_smoothness,worst_compactness,worst_concavity,worst_concave_points,worst_symmetry,worst_fractal_dimension,diagnosis
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,malignant
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,malignant
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,malignant
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,malignant
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,malignant

# Amostragem

Diversos algoritmos de Aprendizagem de Máquina (AM), sejam pela suas complexidades computacionais ou pelas quantidades de memória exigida, apresentam dificuldades em tratar conjuntos de dados de tamanho elevado. Uma quantidade de dados muito grande pode tornar o processo de treinamento demorado.

Um meio de contornar essa dificuldade é a utilização de amostras do conjuntos de dados original. A utilização de um subconjunto menor de objetos, em geral tornará mais simples e rápida a geração de um modelo.


Entretanto, um ponto importante a ser levado em consideração está relacionado ao nível ao qual a amostra representa a distribuição original dos dados.

Normalmente, em casos nos quais a mesma não seja representativa, o modelo de AM induzido não será capaz de atingir uma eficiência aceitável para o problema.

Um modo para tratar o ponto supracitado, resume-se na utilização de técnicas de amostragem estatística, as quais aumentam as chances de que as amostras extraídas da base de dados original possam ser informativas e representativas.

Duas das técnicas mais utilizadas são a amostragem simples e a amostragem estratificada.

Ambas serão introduzidas a seguir.

In [324]:
#Lendo novamente os dados
dados = pd.read_csv('data/breast-cancer.csv')

## Amostragem Simples

A amostragem simples consiste basicamente em extrair objetos, com ou sem reposição, do conjunto de dados original com igual probabilidade.

* No primeiro caso, quando há a reposição, um objeto pode ocorrer mais de uma vez em uma amostra e a probabilidade de ocorrência de cada objeto mantém-se constante durante todo o processo.

* No segundo caso, quando não existe reposição, cada objeto poderá acontecer apenas uma vez em uma amostra. Assim, a probabilidade de ocorrência de cada objeto é alterada a cada passo do processo.

O código abaixo apresenta um exemplo para cada caso.

### Amostragem Simples sem reposição

In [325]:
# gerando uma amostra aleatoria simples de 100 elementos da base Breast Cancer, sem reposicao
amostra_simples_sr=dados.sample(100)
amostra_simples_sr

,sample_id,mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,mean_compactness,mean_concavity,mean_concave_points,mean_symmetry,...,worst_texture,worst_perimeter,worst_area,worst_smoothness,worst_compactness,worst_concavity,worst_concave_points,worst_symmetry,worst_fractal_dimension,diagnosis
309,893548,13.050,13.84,82.71,530.6,0.08352,0.03735,0.004559,0.008829,0.1453,...,17.40,93.96,672.4,0.1016,0.05847,0.01824,0.03532,0.2107,0.06580,benign
372,9012795,21.370,15.10,141.30,1386.0,0.10010,0.15150,0.193200,0.125500,0.1973,...,21.84,152.10,1535.0,0.1192,0.28400,0.40240,0.19660,0.2730,0.08666,malignant
258,887181,15.660,23.20,110.20,773.5,0.11090,0.31140,0.317600,0.137700,0.2495,...,31.64,143.70,1226.0,0.1504,0.51720,0.61810,0.24620,0.3277,0.10190,malignant
208,8810158,13.110,22.54,87.02,529.4,0.10020,0.14830,0.087050,0.051020,0.1850,...,29.16,99.48,639.3,0.1349,0.44020,0.31620,0.11260,0.4128,0.10760,benign
35,854253,16.740,21.59,110.10,869.5,0.09610,0.13360,0.134800,0.060180,0.1896,...,29.02,133.50,1229.0,0.1563,0.38350,0.54090,0.18130,0.4863,0.08633,malignant
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17,84862001,16.130,20.68,108.10,798.8,0.11700,0.20220,0.172200,0.102800,0.2164,...,31.48,136.80,1315.0,0.1789,0.42330,0.47840,0.20730,0.3706,0.11420,malignant
527,91813702,12.340,12.27,78.94,468.5,0.09003,0.06307,0.029580,0.026470,0.1689,...,19.27,87.22,564.9,0.1292,0.20740,0.17910,0.10700,0.3110,0.07592,benign
539,921362,7.691,25.44,48.34,170.4,0.08668,0.11990,0.092520,0.013640,0.2037,...,31.89,54.49,223.6,0.1596,0.30640,0.33930,0.05000,0.2790,0.10660,benign
74,8610175,12.310,16.52,79.19,470.9,0.09172,0.06829,0.033720,0.022720,0.1720,...,23.21,89.71,611.1,0.1176,0.18430,0.17030,0.08660,0.2618,0.07609,benign
385,90291,14.600,23.29,93.97,664.7,0.08682,0.06636,0.083900,0.052710,0.1627,...,31.71,102.20,758.2,0.1312,0.15810,0.26750,0.13590,0.2477,0.06836,malignant

In [326]:
#verificando se há linhas duplicadas
amostra_simples_sr['sample_id'].value_counts()

sample_id
90291       1
893548      1
9012795     1
887181      1
90524101    1
           ..
88995002    1
91227       1
904357      1
8910251     1
914101      1
Name: count, Length: 100, dtype: int64


### Amostragem Simples com reposição

In [327]:
# gerando uma amostra aleatoria simples de 100 elementos da base Breast Cancer, com reposicao
amostra_simples_scr=dados.sample(100, replace=True)
amostra_simples_scr

,sample_id,mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,mean_compactness,mean_concavity,mean_concave_points,mean_symmetry,...,worst_texture,worst_perimeter,worst_area,worst_smoothness,worst_compactness,worst_concavity,worst_concave_points,worst_symmetry,worst_fractal_dimension,diagnosis
287,8913,12.890,13.12,81.89,515.9,0.06955,0.03729,0.02260,0.011710,0.1337,...,15.54,87.40,577.0,0.09616,0.1147,0.11860,0.05366,0.2309,0.06915,benign
532,91903902,13.680,16.33,87.76,575.5,0.09277,0.07255,0.01752,0.018800,0.1631,...,20.20,101.60,773.4,0.12640,0.1564,0.12060,0.08704,0.2806,0.07782,benign
351,899667,15.750,19.22,107.10,758.6,0.12430,0.23640,0.29140,0.124200,0.2375,...,24.17,119.40,915.3,0.15500,0.5046,0.68720,0.21350,0.4245,0.10500,malignant
59,858477,8.618,11.79,54.34,224.5,0.09752,0.05272,0.02061,0.007799,0.1683,...,15.40,59.90,274.9,0.17330,0.1239,0.11680,0.04419,0.3220,0.09026,benign
305,893061,11.600,24.49,74.23,417.2,0.07474,0.05688,0.01974,0.013130,0.1935,...,31.62,81.39,476.5,0.09545,0.1361,0.07239,0.04815,0.3244,0.06745,benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386,902975,12.210,14.09,78.78,462.0,0.08108,0.07823,0.06839,0.025340,0.1646,...,19.29,87.65,529.9,0.10260,0.2431,0.30760,0.09140,0.2677,0.08824,benign
227,88147102,15.000,15.51,97.45,684.5,0.08371,0.10960,0.06505,0.037800,0.1881,...,19.31,114.20,808.2,0.11360,0.3627,0.34020,0.13790,0.2954,0.08362,benign
481,91227,13.900,19.24,88.73,602.9,0.07991,0.05326,0.02995,0.020700,0.1579,...,26.42,104.40,830.5,0.10640,0.1415,0.16730,0.08150,0.2356,0.07603,benign
495,914333,14.870,20.21,96.12,680.9,0.09587,0.08345,0.06824,0.049510,0.1487,...,28.48,103.90,783.6,0.12160,0.1388,0.17000,0.10170,0.2369,0.06599,benign
30,853401,18.630,25.11,124.80,1088.0,0.10640,0.18870,0.23190,0.124400,0.2183,...,34.01,160.50,1670.0,0.14910,0.4257,0.61330,0.18480,0.3444,0.09782,malignant

In [328]:
#verificando se há linhas duplicadas
amostra_simples_scr['sample_id'].value_counts()

sample_id
89827       2
899667      2
91227       2
918465      2
91485       2
           ..
90401601    1
8510426     1
9011494     1
913535      1
91376701    1
Name: count, Length: 91, dtype: int64

## Amostragem estratificada

A amostragem estratificada é tipicamente utilizada quando há o desbalanceamento na quantidade de exemplos de cada classe em um conjunto de dados. Ou seja, neste cenário, normalmente uma ou outra classe possuirá uma quantidade de objetos consideravelmente maior do que as demais.

A fim de gerar um classificador que não seja tendencioso para uma ou mais classes majoritárias ou, de suavizar a dificuldade de modelar alguma das classes de um problema, a amostragem estratificada pode ser utilizada de duas maneiras.

* Na primeira abordagem para amostragem estratificada, o subconjunto a ser extraído contém a mesma quantidade de objetos para cada classe. (**Amostragem Estratificada Uniforme**)

* Na segunda abordagem, a amostra gerada do conjunto de dados original mantém as mesmas proporções de objetos da base de dados original em cada classe. O exemplo de código a seguir demonstra como isso pode ser feito. (**Amostragem Estratificada Proporcional**)

In [329]:
# tamanho da amostra estratificada
tamanho_amostra = 100

In [330]:
# obtendo as classes da base de dados
classes = dados['diagnosis'].unique()
classes

array(['malignant', 'benign'], dtype=object)

### Amostragem Estratificada Uniforme

In [331]:
# Calculando a quantidade de amostras por classe
# Neste exemplo, serao amostradas as mesmas quantidades para cada classe

qtde_por_classe = round(tamanho_amostra / len(classes))

# nesta lista armazenaremos, para cada classe, um pandas.DataFrame com suas amostras
amostras_por_classe = []

In [332]:
for c in classes:

# obtendo os indices do DataFrame
# cujas instancias pertencem a classe c
 indices_c = dados['diagnosis'] == c

# extraindo do DataFrame original as observacoes da
# classe c (obs_c sera um DataFrame tambem)

 obs_c = dados[indices_c]

# extraindo a amostra da classe c
# caso deseje-se realizar amostragem com reposicao ou caso len(obs_c) < qtde_por_classe, pode-se
# informar o parametro replace=True

 amostra_c = obs_c.sample(qtde_por_classe)

# armazenando a amostra_c na lista de amostras

 amostras_por_classe.append(amostra_c)

In [333]:
# concatenando as amostras de cada classe em um único DataFrame
amostra_estr_uniforme = pd.concat(amostras_por_classe)

In [334]:
amostra_estr_uniforme

,sample_id,mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,mean_compactness,mean_concavity,mean_concave_points,mean_symmetry,...,worst_texture,worst_perimeter,worst_area,worst_smoothness,worst_compactness,worst_concavity,worst_concave_points,worst_symmetry,worst_fractal_dimension,diagnosis
373,901288,20.64,17.35,134.80,1335.0,0.09446,0.10760,0.15270,0.08941,0.1571,...,23.17,166.80,1946.0,0.1562,0.3055,0.41590,0.21120,0.2689,0.07055,malignant
72,859717,17.20,24.52,114.20,929.4,0.10710,0.18300,0.16920,0.07944,0.1927,...,33.82,151.60,1681.0,0.1585,0.7394,0.65660,0.18990,0.3313,0.13390,malignant
449,911157302,21.10,20.52,138.10,1384.0,0.09684,0.11750,0.15720,0.11550,0.1554,...,32.07,168.20,2022.0,0.1368,0.3101,0.43990,0.22800,0.2268,0.07425,malignant
254,886226,19.45,19.33,126.50,1169.0,0.10350,0.11880,0.13790,0.08591,0.1776,...,24.57,163.10,1972.0,0.1497,0.3161,0.43170,0.19990,0.3379,0.08950,malignant
205,879523,15.12,16.68,98.78,716.6,0.08876,0.09588,0.07550,0.04079,0.1594,...,20.24,117.70,989.5,0.1491,0.3331,0.33270,0.12520,0.3415,0.09740,malignant
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,871641,11.08,14.71,70.21,372.7,0.10060,0.05743,0.02363,0.02583,0.1566,...,16.82,72.01,396.5,0.1216,0.0824,0.03938,0.04306,0.1902,0.07313,benign
227,88147102,15.00,15.51,97.45,684.5,0.08371,0.10960,0.06505,0.03780,0.1881,...,19.31,114.20,808.2,0.1136,0.3627,0.34020,0.13790,0.2954,0.08362,benign
410,905502,11.36,17.57,72.49,399.8,0.08858,0.05313,0.02783,0.02100,0.1601,...,36.32,85.07,521.3,0.1453,0.1622,0.18110,0.08698,0.2973,0.07745,benign
552,924084,12.77,29.43,81.35,507.9,0.08276,0.04234,0.01997,0.01499,0.1539,...,36.00,88.10,594.7,0.1234,0.1064,0.08653,0.06498,0.2407,0.06484,benign
452,9111843,12.00,28.23,76.77,442.5,0.08437,0.06450,0.04055,0.01945,0.1615,...,37.88,85.07,523.7,0.1208,0.1856,0.18110,0.07116,0.2447,0.08194,benign

In [335]:
#verificando o tamanho da amostra para cada categoria
amostra_estr_uniforme['diagnosis'].value_counts()

diagnosis
malignant    50
benign       50
Name: count, dtype: int64

### Amostragem Estratificada Proporcional

In [336]:
#Lendo novamente os dados
dados = pd.read_csv('data/breast-cancer.csv')

In [337]:
# tamanho da amostra estratificada
tamanho_amostra = 100

In [338]:
# obtendo as classes da base de dados
classes = dados['diagnosis'].unique()

In [339]:
# nesta lista armazenaremos, para cada classe, um
# pandas.DataFrame com suas amostras
amostras_por_classe = []

In [340]:
for c in classes:
# obtendo os indices do DataFrame
# cujas instancias pertencem a classe c
 indices_c = dados['diagnosis'] == c

# extraindo do DataFrame original as observacoes da
# classe c (obs_c sera um DataFrame tambem)
 obs_c = dados[indices_c]

# calculando a proporcao de elementos da classe c
# no DataFrame original
 proporcao_c = len(obs_c) / len(dados)

# calculando a quantidade de elementos da classe
# c que estarao contidos na amostra estratificada
 qtde_c = round(proporcao_c * tamanho_amostra)

# extraindo a amostra da classe c
# caso deseje-se realizar amostra com reposicao ou,
# caso len(obs_c) < qtde_c, pode-se
# informar o parametro replace=True
 amostra_c = obs_c.sample(qtde_c)

# armazenando a amostra_c na lista de amostras
 amostras_por_classe.append(amostra_c)

In [341]:
# concatenando as amostras de cada classe em
# um único DataFrame
amostra_estr_proporcional = pd.concat(amostras_por_classe)

In [342]:
amostra_estr_proporcional

,sample_id,mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,mean_compactness,mean_concavity,mean_concave_points,mean_symmetry,...,worst_texture,worst_perimeter,worst_area,worst_smoothness,worst_compactness,worst_concavity,worst_concave_points,worst_symmetry,worst_fractal_dimension,diagnosis
535,919555,20.550,20.86,137.80,1308.0,0.10460,0.17390,0.208500,0.13220,0.2127,...,25.48,160.20,1809.0,0.1268,0.31350,0.44330,0.21480,0.3077,0.07569,malignant
503,915143,23.090,19.83,152.10,1682.0,0.09342,0.12750,0.167600,0.10030,0.1505,...,23.87,211.50,2782.0,0.1199,0.36250,0.37940,0.22640,0.2908,0.07277,malignant
177,87281702,16.460,20.11,109.30,832.9,0.09831,0.15560,0.179300,0.08866,0.1794,...,28.45,123.50,981.2,0.1415,0.46670,0.58620,0.20350,0.3054,0.09519,malignant
567,927241,20.600,29.33,140.10,1265.0,0.11780,0.27700,0.351400,0.15200,0.2397,...,39.42,184.60,1821.0,0.1650,0.86810,0.93870,0.26500,0.4087,0.12400,malignant
180,873592,27.220,21.87,182.10,2250.0,0.10940,0.19140,0.287100,0.18780,0.1800,...,32.85,220.80,3216.0,0.1472,0.40340,0.53400,0.26880,0.2856,0.08082,malignant
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,906878,13.660,19.13,89.46,575.3,0.09057,0.11470,0.096570,0.04812,0.1848,...,25.50,101.40,708.8,0.1147,0.31670,0.36600,0.14070,0.2744,0.08839,benign
480,912193,12.160,18.03,78.29,455.3,0.09087,0.07838,0.029160,0.01527,0.1464,...,27.87,88.83,547.4,0.1208,0.22790,0.16200,0.05690,0.2406,0.07729,benign
428,90769601,11.130,16.62,70.47,381.1,0.08151,0.03834,0.013690,0.01370,0.1511,...,20.29,74.35,421.1,0.1030,0.06219,0.04580,0.04044,0.2383,0.07083,benign
556,924964,10.160,19.59,64.73,311.7,0.10030,0.07504,0.005025,0.01116,0.1791,...,22.88,67.88,347.3,0.1265,0.12000,0.01005,0.02232,0.2262,0.06742,benign
110,864033,9.777,16.99,62.50,290.2,0.10370,0.08404,0.043340,0.01778,0.1584,...,21.47,71.68,367.0,0.1467,0.17650,0.13000,0.05334,0.2533,0.08468,benign

In [343]:
#verificando o tamanho da amostra para cada categoria
amostra_estr_proporcional['diagnosis'].value_counts()

diagnosis
benign       63
malignant    37
Name: count, dtype: int64

# Dados Ausentes

Dados ausentes podem ocorrer por uma série de motivos em cenários de aplicação reais.

Uma alternativa que pode ser utilizada para a solução de tal problema é a remoção de objetos que contenham valores ausentes.

Entretanto, deve-se perceber que uma grande quantidade de informações relevantes podem acabar sendo descartadas (por exemplo, se muitos objetos possuírem valores ausentes, tem-se uma redução significativa da base de dados).

Portanto, uma alternativa bastante comum é a inserção automática de tais valores, utilizando alguma medida capaz de estimá-los. Comumente, tal medida consiste na média, mediana ou moda do respectivo atributo.

In [344]:
# carrega uma versao do conjunto de dados contendo valores # ausentes
dados_aus = pd.read_csv('data/breast-cancer-missing.csv')

In [345]:
dados_aus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   sample_id                569 non-null    int64
 1   mean_radius              527 non-null    float64
 2   mean_texture             521 non-null    float64
 3   mean_perimeter           508 non-null    float64
 4   mean_area                502 non-null    float64
 5   mean_smoothness          523 non-null    float64
 6   mean_compactness         510 non-null    float64
 7   mean_concavity           502 non-null    float64
 8   mean_concave_points      514 non-null    float64
 9   mean_symmetry            519 non-null    float64
 10  mean_fractal_dimension   513 non-null    float64
 11  radius_error             511 non-null    float64
 12  texture_error            513 non-null    float64
 13  perimeter_error          505 non-null    float64
 14  area_error               509 non-null    float64
 15  smoothness_error         515 non-null    float64
 16  compactness_error        509 non-null    float64
 17  concavity_error          510 non-null    float64
 18  concave_points_error     524 non-null    float64
 19  symmetry_error           511 non-null    float64
 20  fractal_dimension_error  517 non-null    float64
 21  worst_radius             522 non-null    float64
 22  worst_texture            511 non-null    float64
 23  worst_perimeter          503 non-null    float64
 24  worst_area               509 non-null    float64
 25  worst_smoothness         506 non-null    float64
 26  worst_compactness        516 non-null    float64
 27  worst_concavity          519 non-null    float64
 28  worst_concave_points     517 non-null    float64
 29  worst_symmetry           510 non-null    float64
 30  worst_fractal_dimension  494 non-null    float64
 31  diagnosis                505 non-null    object
dtypes: float64(30), int64(1), object(1)
memory usage: 142.4+ KB

In [346]:
#Visualizar os dados ausentes em ordem decrescente de ocorrencias
dados_aus.isnull().sum().sort_values(ascending=False)

worst_fractal_dimension    75
mean_concavity             67
mean_area                  67
worst_perimeter            66
perimeter_error            64
diagnosis                  64
worst_smoothness           63
mean_perimeter             61
area_error                 60
worst_area                 60
compactness_error          60
concavity_error            59
worst_symmetry             59
mean_compactness           59
radius_error               58
symmetry_error             58
worst_texture              58
mean_fractal_dimension     56
texture_error              56
mean_concave_points        55
smoothness_error           54
worst_compactness          53
worst_concave_points       52
fractal_dimension_error    52
mean_symmetry              50
worst_concavity            50
mean_texture               48
worst_radius               47
mean_smoothness            46
concave_points_error       45
mean_radius                42
sample_id                   0
dtype: int64

### Excluindo valores ausentes

Esta é uma decisão mais radical, e deve ser feita apenas em casos em que não haverá impacto significativo no modelo.

Ao eliminar uma linha inteira, você joga fora muita informação que poderia ser extremamente importante.

Essa técnica remove todos os valores NaN encontrados no DataFrame.

In [347]:
# Eliminando todas as linhas relativas à celula contendo o valor ausente
dados_drop1=dados_aus.dropna()
# ou dados_drop=dados_aus.dropna(axis=0)

In [348]:
dados_drop1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 5 to 549
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   sample_id                20 non-null     int64
 1   mean_radius              20 non-null     float64
 2   mean_texture             20 non-null     float64
 3   mean_perimeter           20 non-null     float64
 4   mean_area                20 non-null     float64
 5   mean_smoothness          20 non-null     float64
 6   mean_compactness         20 non-null     float64
 7   mean_concavity           20 non-null     float64
 8   mean_concave_points      20 non-null     float64
 9   mean_symmetry            20 non-null     float64
 10  mean_fractal_dimension   20 non-null     float64
 11  radius_error             20 non-null     float64
 12  texture_error            20 non-null     float64
 13  perimeter_error          20 non-null     float64
 14  area_error               20 non-null     float64
 15  smoothness_error         20 non-null     float64
 16  compactness_error        20 non-null     float64
 17  concavity_error          20 non-null     float64
 18  concave_points_error     20 non-null     float64
 19  symmetry_error           20 non-null     float64
 20  fractal_dimension_error  20 non-null     float64
 21  worst_radius             20 non-null     float64
 22  worst_texture            20 non-null     float64
 23  worst_perimeter          20 non-null     float64
 24  worst_area               20 non-null     float64
 25  worst_smoothness         20 non-null     float64
 26  worst_compactness        20 non-null     float64
 27  worst_concavity          20 non-null     float64
 28  worst_concave_points     20 non-null     float64
 29  worst_symmetry           20 non-null     float64
 30  worst_fractal_dimension  20 non-null     float64
 31  diagnosis                20 non-null     object
dtypes: float64(30), int64(1), object(1)
memory usage: 5.2+ KB

In [349]:
# Eliminando todas as colunas em que existam NaN
dados_drop2=dados_aus.dropna(axis=1)

In [350]:
dados_drop2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 1 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   sample_id  569 non-null    int64
dtypes: int64(1)
memory usage: 4.6 KB

### Preenchendo valores ausentes

Esta abordagem é a mais utilizada, pois você não descarta informação útil.

É necessário escolher qual a métrica será utilizada para preencher os valores ausentes.

Existem técnicas avançadas que são combinadas com o preenchimento de valores, como, por exemplo, analisar correlações ou mesmo construir um modelo preditivo para missing values.

Entretanto, uma abordagem direta e simples consiste em substituir os NaN pela média ou mediana da coluna.

**Preenchendo pela mediana**

In [351]:
dados_aus

,sample_id,mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,mean_compactness,mean_concavity,mean_concave_points,mean_symmetry,...,worst_texture,worst_perimeter,worst_area,worst_smoothness,worst_compactness,worst_concavity,worst_concave_points,worst_symmetry,worst_fractal_dimension,diagnosis
0,842302,17.99,10.38,122.80,NaN,0.11840,0.27760,0.3001,0.14710,NaN,...,17.33,184.60,2019.0,0.1622,0.66560,NaN,0.2654,0.4601,0.11890,malignant
1,842517,20.57,NaN,NaN,1326.0,0.08474,NaN,0.0869,0.07017,0.1812,...,23.41,158.80,1956.0,0.1238,0.18660,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,19.69,21.25,130.00,1203.0,0.10960,NaN,NaN,0.12790,0.2069,...,25.53,152.50,1709.0,0.1444,0.42450,0.4504,0.2430,NaN,0.08758,malignant
3,84348301,11.42,20.38,77.58,386.1,0.14250,0.28390,NaN,0.10520,0.2597,...,26.50,98.87,567.7,0.2098,0.86630,0.6869,0.2575,0.6638,0.17300,malignant
4,84358402,20.29,14.34,135.10,1297.0,0.10030,0.13280,NaN,0.10430,0.1809,...,16.67,152.20,1575.0,0.1374,0.20500,0.4000,0.1625,0.2364,0.07678,malignant
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.2439,0.13890,0.1726,...,26.40,166.10,NaN,0.1410,0.21130,0.4107,0.2216,0.2060,NaN,malignant
565,926682,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.1440,0.09791,0.1752,...,38.25,155.00,1731.0,0.1166,0.19220,0.3215,NaN,0.2572,0.06637,malignant
566,926954,16.60,28.08,108.30,858.1,0.08455,0.10230,NaN,0.05302,0.1590,...,34.12,126.70,1124.0,0.1139,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,NaN,29.33,140.10,1265.0,0.11780,0.27700,0.3514,0.15200,0.2397,...,39.42,184.60,1821.0,0.1650,0.86810,0.9387,0.2650,0.4087,0.12400,malignant
568,92751,7.76,24.54,47.92,NaN,0.05263,0.04362,0.0000,0.00000,0.1587,...,30.37,59.16,268.6,NaN,0.06444,0.0000,0.0000,0.2871,0.07039,NaN

In [352]:
#calculando a mediana dos atributos
mediana=dados_aus.median(numeric_only=True)

In [353]:
#Substitindo os valores ausentes pela mediana do atributo
dados_aus.fillna(mediana, inplace=True)

In [354]:
dados_aus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   sample_id                569 non-null    int64
 1   mean_radius              569 non-null    float64
 2   mean_texture             569 non-null    float64
 3   mean_perimeter           569 non-null    float64
 4   mean_area                569 non-null    float64
 5   mean_smoothness          569 non-null    float64
 6   mean_compactness         569 non-null    float64
 7   mean_concavity           569 non-null    float64
 8   mean_concave_points      569 non-null    float64
 9   mean_symmetry            569 non-null    float64
 10  mean_fractal_dimension   569 non-null    float64
 11  radius_error             569 non-null    float64
 12  texture_error            569 non-null    float64
 13  perimeter_error          569 non-null    float64
 14  area_error               569 non-null    float64
 15  smoothness_error         569 non-null    float64
 16  compactness_error        569 non-null    float64
 17  concavity_error          569 non-null    float64
 18  concave_points_error     569 non-null    float64
 19  symmetry_error           569 non-null    float64
 20  fractal_dimension_error  569 non-null    float64
 21  worst_radius             569 non-null    float64
 22  worst_texture            569 non-null    float64
 23  worst_perimeter          569 non-null    float64
 24  worst_area               569 non-null    float64
 25  worst_smoothness         569 non-null    float64
 26  worst_compactness        569 non-null    float64
 27  worst_concavity          569 non-null    float64
 28  worst_concave_points     569 non-null    float64
 29  worst_symmetry           569 non-null    float64
 30  worst_fractal_dimension  569 non-null    float64
 31  diagnosis                505 non-null    object
dtypes: float64(30), int64(1), object(1)
memory usage: 142.4+ KB

**Preenchendo pela média**

In [355]:
#Lendo os dados novamente
dados_aus = pd.read_csv('data/breast-cancer-missing.csv')

In [356]:
# calculando as medias dos atributos
medias = dados_aus.mean(numeric_only=True)

In [357]:
dados_aus.fillna(medias, inplace=True)

In [358]:
dados_aus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   sample_id                569 non-null    int64
 1   mean_radius              569 non-null    float64
 2   mean_texture             569 non-null    float64
 3   mean_perimeter           569 non-null    float64
 4   mean_area                569 non-null    float64
 5   mean_smoothness          569 non-null    float64
 6   mean_compactness         569 non-null    float64
 7   mean_concavity           569 non-null    float64
 8   mean_concave_points      569 non-null    float64
 9   mean_symmetry            569 non-null    float64
 10  mean_fractal_dimension   569 non-null    float64
 11  radius_error             569 non-null    float64
 12  texture_error            569 non-null    float64
 13  perimeter_error          569 non-null    float64
 14  area_error               569 non-null    float64
 15  smoothness_error         569 non-null    float64
 16  compactness_error        569 non-null    float64
 17  concavity_error          569 non-null    float64
 18  concave_points_error     569 non-null    float64
 19  symmetry_error           569 non-null    float64
 20  fractal_dimension_error  569 non-null    float64
 21  worst_radius             569 non-null    float64
 22  worst_texture            569 non-null    float64
 23  worst_perimeter          569 non-null    float64
 24  worst_area               569 non-null    float64
 25  worst_smoothness         569 non-null    float64
 26  worst_compactness        569 non-null    float64
 27  worst_concavity          569 non-null    float64
 28  worst_concave_points     569 non-null    float64
 29  worst_symmetry           569 non-null    float64
 30  worst_fractal_dimension  569 non-null    float64
 31  diagnosis                505 non-null    object
dtypes: float64(30), int64(1), object(1)
memory usage: 142.4+ KB

**Preenchendo pelo valor mais frequente**

Para atributos categóricos

In [359]:
#Lendo os dados novamente
dados_aus = pd.read_csv('data/breast-cancer-missing.csv')

In [360]:
dados_aus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   sample_id                569 non-null    int64
 1   mean_radius              527 non-null    float64
 2   mean_texture             521 non-null    float64
 3   mean_perimeter           508 non-null    float64
 4   mean_area                502 non-null    float64
 5   mean_smoothness          523 non-null    float64
 6   mean_compactness         510 non-null    float64
 7   mean_concavity           502 non-null    float64
 8   mean_concave_points      514 non-null    float64
 9   mean_symmetry            519 non-null    float64
 10  mean_fractal_dimension   513 non-null    float64
 11  radius_error             511 non-null    float64
 12  texture_error            513 non-null    float64
 13  perimeter_error          505 non-null    float64
 14  area_error               509 non-null    float64
 15  smoothness_error         515 non-null    float64
 16  compactness_error        509 non-null    float64
 17  concavity_error          510 non-null    float64
 18  concave_points_error     524 non-null    float64
 19  symmetry_error           511 non-null    float64
 20  fractal_dimension_error  517 non-null    float64
 21  worst_radius             522 non-null    float64
 22  worst_texture            511 non-null    float64
 23  worst_perimeter          503 non-null    float64
 24  worst_area               509 non-null    float64
 25  worst_smoothness         506 non-null    float64
 26  worst_compactness        516 non-null    float64
 27  worst_concavity          519 non-null    float64
 28  worst_concave_points     517 non-null    float64
 29  worst_symmetry           510 non-null    float64
 30  worst_fractal_dimension  494 non-null    float64
 31  diagnosis                505 non-null    object
dtypes: float64(30), int64(1), object(1)
memory usage: 142.4+ KB

In [361]:
# identificar o valor mais frequente
print(dados_aus.diagnosis.value_counts())
dados_aus_freq= dados_aus.diagnosis.value_counts()[0]

diagnosis
benign       316
malignant    189
Name: count, dtype: int64

/tmp/ipykernel_11256/4013767017.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  dados_aus_freq= dados_aus.diagnosis.value_counts()[0]

In [362]:
# preencher valores ausentes com o valor acima
dados_aus.diagnosis.fillna(dados_aus_freq, inplace=True)

/tmp/ipykernel_11256/583101961.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dados_aus.diagnosis.fillna(dados_aus_freq, inplace=True)

In [363]:
dados_aus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   sample_id                569 non-null    int64
 1   mean_radius              527 non-null    float64
 2   mean_texture             521 non-null    float64
 3   mean_perimeter           508 non-null    float64
 4   mean_area                502 non-null    float64
 5   mean_smoothness          523 non-null    float64
 6   mean_compactness         510 non-null    float64
 7   mean_concavity           502 non-null    float64
 8   mean_concave_points      514 non-null    float64
 9   mean_symmetry            519 non-null    float64
 10  mean_fractal_dimension   513 non-null    float64
 11  radius_error             511 non-null    float64
 12  texture_error            513 non-null    float64
 13  perimeter_error          505 non-null    float64
 14  area_error               509 non-null    float64
 15  smoothness_error         515 non-null    float64
 16  compactness_error        509 non-null    float64
 17  concavity_error          510 non-null    float64
 18  concave_points_error     524 non-null    float64
 19  symmetry_error           511 non-null    float64
 20  fractal_dimension_error  517 non-null    float64
 21  worst_radius             522 non-null    float64
 22  worst_texture            511 non-null    float64
 23  worst_perimeter          503 non-null    float64
 24  worst_area               509 non-null    float64
 25  worst_smoothness         506 non-null    float64
 26  worst_compactness        516 non-null    float64
 27  worst_concavity          519 non-null    float64
 28  worst_concave_points     517 non-null    float64
 29  worst_symmetry           510 non-null    float64
 30  worst_fractal_dimension  494 non-null    float64
 31  diagnosis                569 non-null    object
dtypes: float64(30), int64(1), object(1)
memory usage: 142.4+ KB


# Dados redundantes

Dados redundantes podem ocorrer tanto para os objetos quanto para os atributos de um conjunto de dados [Faceli et al. 2011].

Quando há a redundância de objetos, dois ou mais deles possuem valores muito similares (ou até mesmo iguais) para todos os seus atributos.

Isso pode ser um problema pois, ao aplicar um algoritmo de AM, tais objetos irão inserir uma ponderação artificial aos dados.

Objetos redundantes podem ser removidos por meio do código a seguir.

In [364]:
# Carregando uma versao do conjunto de dados contendo objetos redundantes (repetidos)
dados_red = pd.read_csv('data/breast-cancer-red.csv')

In [365]:
#verificando quantas linhas duplicadas tem no DataSet
dados_red.duplicated().value_counts()

False    569
True      20
Name: count, dtype: int64

In [366]:
dados_red.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 589 entries, 0 to 588
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   sample_id                589 non-null    int64
 1   mean_radius              589 non-null    float64
 2   mean_texture             589 non-null    float64
 3   mean_perimeter           589 non-null    float64
 4   mean_area                589 non-null    float64
 5   mean_smoothness          589 non-null    float64
 6   mean_compactness         589 non-null    float64
 7   mean_concavity           589 non-null    float64
 8   mean_concave_points      589 non-null    float64
 9   mean_symmetry            589 non-null    float64
 10  mean_fractal_dimension   589 non-null    float64
 11  radius_error             589 non-null    float64
 12  texture_error            589 non-null    float64
 13  perimeter_error          589 non-null    float64
 14  area_error               589 non-null    float64
 15  smoothness_error         589 non-null    float64
 16  compactness_error        589 non-null    float64
 17  concavity_error          589 non-null    float64
 18  concave_points_error     589 non-null    float64
 19  symmetry_error           589 non-null    float64
 20  fractal_dimension_error  589 non-null    float64
 21  worst_radius             589 non-null    float64
 22  worst_texture            589 non-null    float64
 23  worst_perimeter          589 non-null    float64
 24  worst_area               589 non-null    float64
 25  worst_smoothness         589 non-null    float64
 26  worst_compactness        589 non-null    float64
 27  worst_concavity          589 non-null    float64
 28  worst_concave_points     589 non-null    float64
 29  worst_symmetry           589 non-null    float64
 30  worst_fractal_dimension  589 non-null    float64
 31  diagnosis                589 non-null    object
dtypes: float64(30), int64(1), object(1)
memory usage: 147.4+ KB

**Eliminando redundância de unidades amostrais, ou seja, de linhas.**

In [367]:
# Removendo exemplos redundantes
# (Observe que o resultado sera a base original
# O parametro inplace determina se a alteracao deve ocorrer no proprio DataFrame.
# Portanto, caso inplace=False, a funcao drop_duplicates retorna uma copia de breast_cancer_red com os exemplos redundantes removidos.)

dados_red.drop_duplicates(inplace=True)

In [368]:
dados_red.info()

<class 'pandas.core.frame.DataFrame'>
Index: 569 entries, 0 to 588
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   sample_id                569 non-null    int64
 1   mean_radius              569 non-null    float64
 2   mean_texture             569 non-null    float64
 3   mean_perimeter           569 non-null    float64
 4   mean_area                569 non-null    float64
 5   mean_smoothness          569 non-null    float64
 6   mean_compactness         569 non-null    float64
 7   mean_concavity           569 non-null    float64
 8   mean_concave_points      569 non-null    float64
 9   mean_symmetry            569 non-null    float64
 10  mean_fractal_dimension   569 non-null    float64
 11  radius_error             569 non-null    float64
 12  texture_error            569 non-null    float64
 13  perimeter_error          569 non-null    float64
 14  area_error               569 non-null    float64
 15  smoothness_error         569 non-null    float64
 16  compactness_error        569 non-null    float64
 17  concavity_error          569 non-null    float64
 18  concave_points_error     569 non-null    float64
 19  symmetry_error           569 non-null    float64
 20  fractal_dimension_error  569 non-null    float64
 21  worst_radius             569 non-null    float64
 22  worst_texture            569 non-null    float64
 23  worst_perimeter          569 non-null    float64
 24  worst_area               569 non-null    float64
 25  worst_smoothness         569 non-null    float64
 26  worst_compactness        569 non-null    float64
 27  worst_concavity          569 non-null    float64
 28  worst_concave_points     569 non-null    float64
 29  worst_symmetry           569 non-null    float64
 30  worst_fractal_dimension  569 non-null    float64
 31  diagnosis                569 non-null    object
dtypes: float64(30), int64(1), object(1)
memory usage: 146.7+ KB

In [369]:
dados_red.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
584    False
585    False
586    False
587    False
588    False
Length: 569, dtype: bool

In [370]:
#verificando quantas linhas duplicadas tem no DataSet
dados_red.duplicated().value_counts()

False    569
Name: count, dtype: int64

**A eliminação de redundâncias de atributos será estudo mais para frente.**